export const PROVINCE = [
  { v: "AG", l: "Agrigento" }, { v: "AL", l: "Alessandria" }, { v: "AN", l: "Ancona" },
  { v: "AO", l: "Aosta" }, { v: "AR", l: "Arezzo" }, { v: "AP", l: "Ascoli Piceno" },
  { v: "AT", l: "Asti" }, { v: "AV", l: "Avellino" }, { v: "BA", l: "Bari" },
  { v: "BT", l: "Barletta-Andria-Trani" }, { v: "BL", l: "Belluno" }, { v: "BN", l: "Benevento" },
  { v: "BG", l: "Bergamo" }, { v: "BI", l: "Biella" }, { v: "BO", l: "Bologna" },
  { v: "BZ", l: "Bolzano" }, { v: "BS", l: "Brescia" }, { v: "BR", l: "Brindisi" },
  { v: "CA", l: "Cagliari" }, { v: "CL", l: "Caltanissetta" }, { v: "CB", l: "Campobasso" },
  { v: "CE", l: "Caserta" }, { v: "CT", l: "Catania" }, { v: "CZ", l: "Catanzaro" },
  { v: "CH", l: "Chieti" }, { v: "CO", l: "Como" }, { v: "CS", l: "Cosenza" },
  { v: "CR", l: "Cremona" }, { v: "KR", l: "Crotone" }, { v: "CN", l: "Cuneo" },
  { v: "EN", l: "Enna" }, { v: "FM", l: "Fermo" }, { v: "FE", l: "Ferrara" },
  { v: "FI", l: "Firenze" }, { v: "FG", l: "Foggia" }, { v: "FC", l: "Forlì-Cesena" },
  { v: "FR", l: "Frosinone" }, { v: "GE", l: "Genova" }, { v: "GO", l: "Gorizia" },
  { v: "GR", l: "Grosseto" }, { v: "IM", l: "Imperia" }, { v: "IS", l: "Isernia" },
  { v: "SP", l: "La Spezia" }, { v: "AQ", l: "L'Aquila" }, { v: "LT", l: "Latina" },
  { v: "LE", l: "Lecce" }, { v: "LC", l: "Lecco" }, { v: "LI", l: "Livorno" },
  { v: "LO", l: "Lodi" }, { v: "LU", l: "Lucca" }, { v: "MC", l: "Macerata" },
  { v: "MN", l: "Mantova" }, { v: "MS", l: "Massa-Carrara" }, { v: "MT", l: "Matera" },
  { v: "ME", l: "Messina" }, { v: "MI", l: "Milano" }, { v: "MO", l: "Modena" },
  { v: "MB", l: "Monza e Brianza" }, { v: "NA", l: "Napoli" }, { v: "NO", l: "Novara" },
  { v: "NU", l: "Nuoro" }, { v: "OR", l: "Oristano" }, { v: "PD", l: "Padova" },
  { v: "PA", l: "Palermo" }, { v: "PR", l: "Parma" }, { v: "PV", l: "Pavia" },
  { v: "PG", l: "Perugia" }, { v: "PU", l: "Pesaro e Urbino" }, { v: "PE", l: "Pescara" },
  { v: "PC", l: "Piacenza" }, { v: "PI", l: "Pisa" }, { v: "PT", l: "Pistoia" },
  { v: "PN", l: "Pordenone" }, { v: "PZ", l: "Potenza" }, { v: "PO", l: "Prato" },
  { v: "RG", l: "Ragusa" }, { v: "RA", l: "Ravenna" }, { v: "RC", l: "Reggio Calabria" },
  { v: "RE", l: "Reggio Emilia" }, { v: "RI", l: "Rieti" }, { v: "RN", l: "Rimini" },
  { v: "RM", l: "Roma" }, { v: "RO", l: "Rovigo" }, { v: "SA", l: "Salerno" },
  { v: "SS", l: "Sassari" }, { v: "SV", l: "Savona" }, { v: "SI", l: "Siena" },
  { v: "SR", l: "Siracusa" }, { v: "SO", l: "Sondrio" }, { v: "SU", l: "Sud Sardegna" },
  { v: "TA", l: "Taranto" }, { v: "TE", l: "Teramo" }, { v: "TR", l: "Terni" },
  { v: "TO", l: "Torino" }, { v: "TP", l: "Trapani" }, { v: "TN", l: "Trento" },
  { v: "TV", l: "Treviso" }, { v: "TS", l: "Trieste" }, { v: "UD", l: "Udine" },
  { v: "VA", l: "Varese" }, { v: "VE", l: "Venezia" }, { v: "VB", l: "Verbano-Cusio-Ossola" },
  { v: "VC", l: "Vercelli" }, { v: "VR", l: "Verona" }, { v: "VV", l: "Vibo Valentia" },
  { v: "VI", l: "Vicenza" }, { v: "VT", l: "Viterbo" },
];
